### PR TITLE
Take negative run numbers for MC

### PR DESCRIPTION
**Pull request by jmbenlloch**
This PR changes the way we use the DB. Instead of using just run number 0 for MC, now the idea is to put a negative number. The configuration obtained will be the same as the one from the same positive run number. The negative sign will indicate that is an MC file.

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
Travis is unhappy. Any idea why, @jmbenlloch ?

**Comment by jmbenlloch** [comment]
It is strange, in my fork travis was not complaining... I'm looking at it.

**Comment by jmbenlloch** [comment]
It is already fixed, it was a problem with the dev db. You should redownload dev db again.

**Review by jjgomezcadenas — APPROVED** [review]
Updates in the DB needed for the MC to have the same configuration than the data (e.g, for the elecID in the PMTs). The new dev DB also introduces masked SiPMs.

**Comment by jjgomezcadenas** [comment]
please merge @jmbenlloch

**Comment by jmbenlloch** [comment]
Done.

**Pull request merged**
