### PR TITLE
Add test suite for configure module.

### PR DESCRIPTION
**Pull request by jjgomezcadenas**
There was a subtle and hard-to-catch "bug" in configure.py. The bug
itself appears to be in argparse which in python 3 will not take an
int as an argument (as was the case in python2.7). The fix is simply
to modify the argument to str and later cast to int.

A test suite has been added, and a notebook describing the issue is
avaialble at
https://anaconda.org/nexticw/configure_test/notebook

Notice that diomira.ipynb is deleted in this commit. This goes in line
with the policy to hold all notebooks (including those of IC) in ICARO.

### CODE REVIEW

**Comment by jacg** [comment]
The bug description sounds fishy: argparse in Python 3 *should* accept `int`s as arguments. Initial ad-hoc testing suggests that it *does* accept them. Then I reverted the changes to `configure.py`, ran the test, and the test passes.

So, I love the idea of the test being added, but I can't reproduce the bug, and therefore the bug fix looks to me like an unnecessary complication, which makes code uglier for no good reason.

Is this some kind of Mac-only thing?

I'm about to push a cosmetic modification to the test.

**Comment by jjgomezcadenas** [comment]
Very strange. Look at the associated notebook to see the error. I definitively have it, unless I miss something…

**Comment by jacg** [comment]
> Look at the associated notebook to see the error.

The problem with the associated notebook is that I can't see the wood for the trees. Does it really take 18 input cells an and argparse configuration with 9 defined arguments, to demonstrate the presence of this bug?

Please get into the habit of preparing *minimal working examples*: something that demonstrates the presence of a bug with the **minimal** amount of code, excluding everything is not necessary to show the presence of the bug. Once you have a *minimal* working example, that should be wrapped up to make your first test.

**Comment by jjgomezcadenas** [comment]
With all due respect, I think the nb has some logic. Please bear with me:

function configure_bug <http://localhost:8888/notebooks/ICARO/invisible_cities/core/configure_test.ipynb#function-configure_bug>
configure_bug corresponds to the configure.py function being fixed. It declares parameters 'n', 's' and 'p' of integer type. For some reason this does not seem to work in python3.

It declares the problem and defines in the NB itself the function configure_bug which is a straight copy of configure.py, adding a couple of printouts to illustrate the exact point where the crash is going to occur. 

def configure_bug(input_options=sys.argv):
    """Translate command line options to a meaningfull dictionary.

    Parameters
    ----------
    input_options : sequence of strings, optional
        Input flags and parameters. Default are command line options from
        sys.argv.

    Returns
    -------
    output_options : dictionary
        Options as key-value pairs.
    “""

Just the configure.py function with the printout


def crash_configure_bug(rwf_file, pmp_file, conf_file, n_events= 1, store_pmaps=False):
    """Run Irene."""
    print('n_events = {} type of n_events = {}'.format(n_events,type(n_events)))
    print('This will crash now')
    CFP = configure_bug(['IRENE',
                     '-c', conf_file,
                     '-i', rwf_file,
                     '-o', pmp_file,
                     '-n', n_events])

A function that will make the configure crash, the deal is that n is integer.

The crash itself

crash_configure_bug(RWF_file, PMP_file, CONF_file_def, n_events= 1, store_pmaps=False)

n_events = 1 type of n_events = <class 'int'>
This will crash now
IRENE ['-c', '/Users/jjgomezcadenas/Projects/IC/invisible_cities//config/irene.conf', '-i', '/Users/jjgomezcadenas/Projects/ICDATA/electrons_40keV_z250_RWF.h5', '-o', '/Users/jjgomezcadenas/Projects/ICDATA/electrons_40keV_z250_PMAP.h5', '-n', 1]
program will crash after this line, trying to process nevt as int
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-ee4d232e8782> in <module>()
----> 1 crash_configure_bug(RWF_file, PMP_file, CONF_file_def, n_events= 1, store_pmaps=False)

<ipython-input-18-547938c50e6d> in crash_configure_bug(rwf_file, pmp_file, conf_file, n_events, store_pmaps)
      7                      '-i', rwf_file,
      8                      '-o', pmp_file,
----> 9                      '-n', n_events])



function configure_fix <http://localhost:8888/notebooks/ICARO/invisible_cities/core/configure_test.ipynb#function-configure_fix>function configure_fix fixes the problem declaring the int variables as str and casting the int type when passing to opts.

The fix, (take str rather than int)

def configure_fix(input_options=sys.argv):
    """Translate command line options to a meaningfull dictionary.

    Parameters
    ----------
    input_options : sequence of strings, optional
        Input flags and parameters. Default are command line options from
        sys.argv.

    Returns
    -------
    output_options : dictionary
        Options as key-value pairs.
    """
    print('configure')
    program, args = input_options[0], input_options[1:]
    print(program, args)
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", metavar="cfile", type=str,
                        help="configuration file", required=True)
    parser.add_argument("-i", metavar="ifile", type=str,
                        help="input file")
    parser.add_argument("-o", metavar="ofile", type=str,
                        help="output file")
    parser.add_argument("-n", metavar="nevt", type=str,
                        help="number of events to be processed")
    parser.add_argument("-s", metavar="skip", type=str, default=0,
                        help="number of events to be skipped")
    parser.add_argument("-p", metavar="print_mod", type=str,
                        help="print every this number of events")
    parser.add_argument("--runall", action="store_true",
                        help="number of events to be skipped")
    parser.add_argument("-I", action="store_true", help="print info")
    parser.add_argument("-v", action="count", help="verbosity level")


A test on the function:

def test_configure_simple():
    """Test configure function. Only input parameters"""
    
    n = 10
    s = 0
    p = 1
    CFP = configure_fix(['program_name',
                     '-c', CONF_file_def,
                     '-i', 'rwf_file',
                     '-o', 'pmp_file',
                     '-n', str(n),
                     '-s', str(s),
                     '-p', str(p)])
    
    assert CFP["FILE_IN"] == 'rwf_file'
    assert CFP["FILE_OUT"] == 'pmp_file'
    assert CFP["NEVENTS"] == 10
    assert CFP["SKIP"] == 0
    assert CFP["PRINT_MOD"] == 1

And a final test that checks all parameters.
def test_configure_fix():
    """Test fixed configure function. Read from conf file"""


….

I believe the logic is not completely insane. In any case, as you can see, what makes the program crash is this line:

print('program will crash after this line, trying to process nevt as int')
    parser.add_argument("-n", metavar="nevt", type=int,
                        help="number of events to be processed”)

And the program does not crash if replaced by:

    parser.add_argument("-n", metavar="nevt", type=str,
                        help="number of events to be processed")

At any rate, the test just checks that all values are as they should be, so I think the test is correct and you can understand easily the source of the error.

**Comment by jacg** [comment]
With all due respect, maybe the notebook has some logic, but if you want people to help you, don't ask them to bear with you as you drown them in a deluge of seemingly irrelevant information. (Hint: I remind you that the test passes without the fix! Write me a test that fails without the fix.) I have very limited time before I have to go away. I've already struggled, with `IC_DATA`. I found something about that in `doc/notebooks.rst`. So I set it, and now the NB crashes on `IC_CONFIG`. So I'm trawling through our documentation to find out what the hell that should be set to. Combine this with the time I have already dedicated to trying to find the needle in the haystack that is the notebook, and 10 or 15 minutes of my time have already gone, and I'm no closer to understanding what's going on. I'm about to leave, and when I next have some time to dedicate to IC, I'll be tempted to look at something less frustrating than this issue.

Give me something that works *out of the box*, and demonstrates the problem, without pages and pages of irrelevant context, and I'm so much more likely to

1. be inclined to look at it
1. understand the problem
1. be able to help you

Flooding me with a 3 page long copy-paste, in response to me pointing out that you are flooding me with excessive irrelevant information, seems rather odd.

It's really important that you get used to preparing **minimal** working examples. Ones that *work out of the box*!

I don't want a notebook, I want an *automated* test, that shows the problem. (And please make it *minimal*!) If you want to explain the reasoning behind the test in greater detail, by all means use a notebook. But if there is no failing *automated* test, there is nothing to talk about.

**Comment by jacg** [comment]
> function configure_bug <http://localhost:8888/notebooks/ICARO/invisible_cities/core/configure_test.ipynb#function-configure_bug> configure_bug corresponds to the configure.py function being fixed. It declares parameters 'n', 's' and 'p' of integer type. For some reason this does not seem to work in python3.

Please put this in a *minimal* failing test that I can run without having to set all sorts of things manually. I should be able to pull the branch containing this test, type `bash manage.sh compile_and_test` and the test suite should point me to the error.

(Hint: the process of preparing a **minimal** working case often leads you to the discovery of the problem!)

**Comment by jacg** [comment]
I extracted the following code from your notebook, removing any unnecessary and distracting dependences on `IC` stuff. Saving this in a file and executing it with Python 2 gives an error which is effectively identical to the error that appears when executing it with Python 3.

    import sys
    import argparse
    
    def crash_configure_bug(rwf_file, pmp_file, conf_file, n_events= 1, store_pmaps=False):
        """Run Irene."""
        print('n_events = {} type of n_events = {}'.format(n_events,type(n_events)))
        print('This will crash now')
        CFP = configure_bug(['IRENE',
                         '-c', conf_file,
                         '-i', rwf_file,
                         '-o', pmp_file,
                         '-n', n_events])
    
    def configure_bug(input_options=sys.argv):
        """Translate command line options to a meaningfull dictionary.
    
        Parameters
        ----------
        input_options : sequence of strings, optional
            Input flags and parameters. Default are command line options from
            sys.argv.
    
        Returns
        -------
        output_options : dictionary
            Options as key-value pairs.
        """
        program, args = input_options[0], input_options[1:]
        print(program, args)
        parser = argparse.ArgumentParser()
        
        parser.add_argument("-c", metavar="cfile", type=str,
                            help="configuration file", required=True)
        parser.add_argument("-i", metavar="ifile", type=str,
                            help="input file")
        parser.add_argument("-o", metavar="ofile", type=str,
                            help="output file")
       
        print('program will crash after this line, trying to process nevt as int')
        parser.add_argument("-n", metavar="nevt", type=int,
                            help="number of events to be processed")
        
        parser.add_argument("-s", metavar="skip", type=int, default=0,
                            help="number of events to be skipped")
        parser.add_argument("-p", metavar="print_mod", type=int,
                            help="print every this number of events")
        parser.add_argument("--runall", action="store_true",
                            help="number of events to be skipped")
        parser.add_argument("-I", action="store_true", help="print info")
        parser.add_argument("-v", action="count", help="verbosity level")
    
        flags, extras = parser.parse_known_args(args)
        options = conf.read_config_file(flags.c) if flags.c else {}
        
        if flags.i is not None:
            options["FILE_IN"] = flags.i
        if flags.o is not None:
            options["FILE_OUT"] = flags.o
        if flags.n is not None:
            options["NEVENTS"] = flags.n
        if flags.s is not None:
            options["SKIP"] = flags.s
        if flags.p is not None:
            options["PRINT_MOD"] = flags.p
        if flags.runall:
            options["RUN_ALL"] = flags.runall
        options["INFO"] = flags.I
        if flags.v is not None:
            options["VERBOSITY"] = 50 - min(flags.v, 4)*10
    
    
        conf.print_configuration(options)
        return options
    
    crash_configure_bug('hello', 'goodbye', 'blabla', n_events= 1, store_pmaps=False)

**Comment by jjgomezcadenas** [comment]
Sorry about the mess, I now understand that the nb was clearer for me than for you. Please look at the new PR. I have reverted the code to the “unfixed” status and added a test that fails for python3 in the Mac OS X. Please check if it fails for you.

**Comment by jjgomezcadenas** [comment]
If you confirm that it fails, I can submit the fixed version of the code that will not fail

**Comment by jacg** [comment]
From the above, I have extracted the **minimal** (or close to it) example:

    import sys
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("-n", metavar="nevt", type=int, help="h")
    parser.parse_known_args(['-n', 1])

Anynone looking at this, doesn't have to look for a needle in a haystack, and doesn't have to mess around for half an hour manually setting all sorts of environment variables to demonstrate the problem, doesn't need to have IC installed. Like this, you can show it to *anyone* and within seconds said person will be able to start thinking about your problem, rather than 20 other problems you have caused for that person.

**Minimal** working examples are *essential* for communicating these sorts of things.

Now that we have a minimal working example, there's an obvious experiment to try ... turn that `1` on the last line into a `'1'` ... and it doesn't crash. Hmm ... even though you have instructed argparse that this argument should be an integer, the raw information that argparse receives is still a string. You seem to be feeding it a (python) integer. I suspect that that's your problem right there: GIGO.

Dinner time.

**Comment by jjgomezcadenas** [comment]
Yes. In python 2.7, when you ask python for the type of the object it tells you is an int. In Python 3.5 is class<int>. So I believe argparse is having issues.

**Comment by jacg** [comment]
Where and how do you ask python for the type? Show me a minimal working example please.

**Pull request closed without merging**
