### PR TITLE
Add tests for the BLR algorithm

### PR DESCRIPTION
**Pull request by gonzaponte**
Somehow the module `sierpe/blr.pyx` has managed to escape the master's radar until now. This PR introduces some tests to this code, which belongs to the core of our processing chain. There are two types of tests:

- Property checking: by using a toy signal, we check that the integral is positive and that the baseline is recovered.

- Stability: by using some real waveforms we store the current value of the blr waveform in order to have something to compare with in the future. This assumes we trust the current algorithm.

### CODE REVIEW

**Comment by gonzaponte** [comment]
I would like to read opinions about everything but in particular about the comments in the tests named `*ad_hoc_signals*`.

**Review by jjgomezcadenas — APPROVED** [review]
Very good. There was plenty of tests and studies for BLR but they never made it to IC. Good work!

**Comment by gonzaponte** [comment]
Don't merge, this is still work in progress.

**Comment by jjgomezcadenas** [comment]
Actually, I think no more tests are needed for this function. Please wrap up and let's move to something else.

**Comment by gonzaponte** [comment]
There is one more test to be included which should verify the filtering behavior of `deconv_pmt`. Tomorrow.

**Pull request merged**
