### PR TITLE
Adds fix for Mac in init.el

### PR DESCRIPTION
**Pull request by jerenner**

### CODE REVIEW

**Comment by gonzaponte** [comment]
What does it do exactly?

**Comment by jerenner** [comment]
It allowed access of git lfs from within Magit which was not working previously on my (Mac) machine

**Comment by jacg** [comment]
> What does it do exactly?

Window-based applications on the Mac do not inherit the environment from any shell. This includes Emacs, when it is launched by clicking on an icon. This PR extents the `docs/init.el` so that itinstalls the emacs package `exec-path-from-shell` which ensures that Emacs uses the `PATH` specification that you configure in your shell resource files.

This has the efffect of fixing all sorts of things that should work in Emacs but are broken on Macs, among them `git lfs`. Specifically, it enables you to use magit with the LFS-ized version of IC.

**Review by jacg — APPROVED** [review]
Makes Emacs work more sensibly for Mac users.

As it's not IC Python code, no tests are needed or sensibly possible.

**Pull request merged**
