### PR TITLE
fix bug in hist2d_profile

### PR DESCRIPTION
**Pull request by gonzaponte**
There was a confusion between two variables that was visible only when the number of bins in the two coordinates was different. This PR fixes it.

### CODE REVIEW

**Comment by gonzaponte** [comment]
I can't reproduce the error in my computer. I think it has something to do with matplotlib. Ideas?

**Comment by jjgomezcadenas** [comment]
The problem is related with the back-end of matplotlib. In short, **do not involve matplotlib in tests** at least for the time being. The best approach here would be to decouple the matplotlib part from the math part, and just test the math part.

**Comment by gonzaponte** [comment]
The problem in this case is that the test uses the output of the matplotlib part... The workflow is:
1. Do a profileXY (this function is already tested)
2. Reorganize the output of this function
3. Input the reorganized data to hist2d (which is just a wrapper of matplotlib's hist2d)

And the test aims to:
1. Check that the output of profileXY makes sense. I am trying to check that the function has been coded correctly, independently of profileXY working fine. I may have entered into the reinventing-the-wheel zone, though.

2. Check that the output of hist2d makes sense. We actually would only like to check that the data is input properly (provided that the function is already tested), but we can't do that that so we check the output instead.

**Comment by jjgomezcadenas** [comment]
Well, we have to find away to get rid of matplotlib in tests.

**Comment by jjgomezcadenas** [comment]
What about this @gonzaponte ?

**Comment by gonzaponte** [comment]
I have plans to split the function in two. I can do it this week, I think.

**Comment by gonzaponte** [comment]
I think this is a bit obsolete. I will create a new PR with many miscellaneous functions for icaro that include issues from this PR.

**Pull request closed without merging**
