### PR TITLE
Generalize city input files

### PR DESCRIPTION
**Pull request by gonzaponte**
So far we could only deal with either a single file or a wildcard. This PR extends it to accept lists of files and lists of wildcards.

### CODE REVIEW

**Comment by jwaiton** [comment]
Looks good! The code allows for multiple input files to be introduced as is demonstrated within the test, which passes on my system.

I didn't find it intuitive to alter a config file such that it allowed for a list of files to be processed at once, perhaps I am expecting behaviour that isn't intended in this PR. Is the intended behaviour that multiple h5 input files can be piped into a singular output file? If this is the intended behaviour, it may be helpful to include some sort of formatting help in the template config files to explain how to implement this.

I also tested an edge case in which someone inserts a list including both a wildcard and a specific file (which should result in an overlap of the input files), and added it [here](https://github.com/next-exp/IC/pull/877/files#diff-79c16ea78db6a7806308d8f3865a58cbbcd296763e68133b6445ee71bc4ffba9R89) as such:

```
@mark.parametrize( "case_ files_in expected".split()
                 , ( ( 0
                     , "electrons_511keV_z250_RWF.h5"  # a single file without wildcard
                     , "electrons_511keV_z250_RWF.h5")
                   , ( 1
                     , "electrons_*keV_z250_RWF.h5"   # a single wildcard leading to three files
                     , ["electrons_511keV_z250_RWF.h5" , "electrons_1250keV_z250_RWF.h5", "electrons_2500keV_z250_RWF.h5"])
                   , ( 2
                     , [ "electrons_511keV_z250_RWF.h5", "electrons_1250keV_z250_RWF.h5"] # a list of two files without wildcards
                     , [ "electrons_511keV_z250_RWF.h5", "electrons_1250keV_z250_RWF.h5"] )
                   , ( 3
                     , [ "electrons_5*keV_z250_RWF.h5", "electrons_1*keV_z250_RWF.h5"] # a list of wildcards leading to n files
                     , [ "electrons_511keV_z250_RWF.h5", "electrons_1250keV_z250_RWF.h5"] )
                    , (4
                     , [ "electrons_*keV_z250_RWF.h5", "electrons_1250keV_z250_RWF.h5"] # a list with an overlapping wildcard leading to n files
                     , ["electrons_511keV_z250_RWF.h5" , "electrons_1250keV_z250_RWF.h5", "electrons_2500keV_z250_RWF.h5"] )
                   )
                 )
```

This returned the error:

```
E       AssertionError: assert ['/home/e7836..._z250_RWF.h5'] == ['/home/e7836..._z250_RWF.h5']
E         At index 1 diff: '/home/e78368jw/Documents/NEXT_CODE/IC/invisible_cities/database/test_data/electrons_1250keV_z250_RWF.h5' != '/home/e78368jw/Documents/NEXT_CODE/IC/invisible_cities/database/test_data/electrons_2500keV_z250_RWF.h5'
E         Left contains one more item: '/home/e78368jw/Documents/NEXT_CODE/IC/invisible_cities/database/test_data/electrons_511keV_z250_RWF.h5'
E         Use -v to get the full diff

invisible_cities/cities/components_test.py:144: AssertionError

```
This test fails I believe due to the output of the test having two instances of `electrons_1250keV_z250_RWF.h5`. This is an unlikely edge case that I would consider only occurring due to user error, and the consequence I can see is that perhaps a file is processed twice within a single output, which may have unforeseen issues in certain cities. 

Would it be worth adding a check to ensure that if duplicate input files are found, the duplicates are removed?

**Comment by gonzaponte** [comment]
> I didn't find it intuitive to alter a config file such that it allowed for a list of files to be processed at once, perhaps I am expecting behaviour that isn't intended in this PR

It is very much intended, it should be as easy as `files_in = [file_1, file_2, ...]` and I'm surprised that it didn't work. A bit silly of me not to have tried that myself. This calls for another test, which I will implement.

> This test fails I believe due to the output of the test having two instances of `electrons_1250keV_z250_RWF.h5`.

Indeed. Adding this case is an excellent idea.

> perhaps a file is processed twice within a single output, which may have unforeseen issues in certain cities.
> Would it be worth adding a check to ensure that if duplicate input files are found, the duplicates are removed?

It is a weird case and I'm unsure how much effort to put into it. I'm tempted to raise a warning and carry on with the set of unique files. It's hard to imagine a sensible behaviour that doesn't involve ignoring the duplicate file.

**Comment by jwaiton** [comment]
> It is very much intended, it should be as easy as `files_in = [file_1, file_2, ...]` and I'm surprised that it didn't work.

I believe this was just a silly issue with formatting on my part. The correct format is `files_in = ['file_1', 'file_2', ...]` which works as expected. This didn't work for me initially (due to a typo in retrospect I think) so I tried all other formatting possibilities to no avail. 

It may be useful to have the format for `files_in` in an example config file somewhere, but I think that may be overkill.

> It is a weird case and I'm unsure how much effort to put into it. I'm tempted to raise a warning and carry on with the set of unique files. It's hard to imagine a sensible behaviour that doesn't involve ignoring the duplicate file.

I think that would be perfect :)

**Comment by gonzaponte** [comment]
>  The correct format is `files_in = ['file_1', 'file_2', ...]` which works as expected

Indeed. Config files are just python files with some magic applied behind the scenes. Filenames must be quoted to be interpreted as strings. I've added a comment that hopefully clarifies the syntax. Let me know what you think.
We will have to add this behaviour to the documentation and clarify the syntax there as well.

> I'm surprised that it didn't work. A bit silly of me not to have tried that myself. This calls for another test, which I will implement.

My memory failed me. I did not remember that the test writes config files already, so this is covered.

**Comment by jwaiton** [comment]
> I've added a comment that hopefully clarifies the syntax. Let me know what you think.

The comment is perfect. :)

I've rerun the tests with the new case, everything passed. This change allows for lists of input files and lists of wildcards to be used rather than singular files and wildcards. Good work!

**Review by jwaiton — APPROVED** [review]
This change allows for lists of input files and lists of wildcards to be used rather than singular files and wildcards. Good work!

**Pull request merged**
