### PR TITLE
Add parameter to reduce fit range externally

### PR DESCRIPTION
**Pull request by gonzaponte**
This PR introduces a new, very useful functionality to the fit function. The fitting range can be tuned externally without typing 3 very noise lines of code.

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
Do you have a test to check that the new parameter does not introduce a bug?

**Comment by gonzaponte** [comment]
I do now

**Review by jjgomezcadenas — APPROVED** [review]
This is a simple (and useful) improvement of the fit function module, with its corresponding test.

**Comment by jjgomezcadenas** [comment]
PR approved. Please, squash.

**Comment by gonzaponte** [comment]
Squashed.

**Pull request merged**
