### PR TITLE
Irene jck

### PR DESCRIPTION
**Pull request by jjgomezcadenas**
This PR completes the evolution of Irene.py towards a JCK-1 syntax.

### CODE REVIEW

**Review by jmbenlloch — APPROVED** [review]

**Comment by jacg** [comment]
Note that this PR contained commits which were already in `nextic/master`. You should have rebased.

**Comment by jjgomezcadenas** [comment]
I know, sorry!

**Comment by jacg** [comment]
I would also recommend replacing

    self.nprint       = 1000000
    self.signal_start = 0
    self.signal_end   = 1200
    self.ymax         = 200
    self.S1_start     = 100
    self.S1_end       = 100.5
    self.S1_ymax      = 5

with
    
    self.nprint       = 1000000
    self.signal_start =       0
    self.signal_end   =    1200
    self.ymax         =     200
    self.S1_start     =     100
    self.S1_end       =     100.5
    self.S1_ymax      =       5
    
though I would also consider
    
    self.nprint       = 1000000
    self.signal_start =    0
    self.signal_end   = 1200
    self.ymax         =  200
    self.S1_start     =  100
    self.S1_end       =  100.5
    self.S1_ymax      =    5

**Comment by jacg** [comment]
Similarly

    row["time"] = time[j]
    row["ene"]  = ene[j]

might be replaced with

    row["time"] = time[j]
    row["ene"]  =  ene[j]

To highlight the matching subscripts.

**Comment by jacg** [comment]
`assert` is a keyword, not a function, so 

    assert(len(time) == len(ene))

should be

    assert len(time) == len(ene)

**Comment by jacg** [comment]
Here    

     .format(self.tmin_s2 / units.mus,
             self.tmax_s2 / units.mus,
             self.stride_s2,
             self.lmin_s2,
             self.lmax_s2))

you might consider

     .format(self.  tmin_s2 / units.mus,
             self.  tmax_s2 / units.mus,
             self.stride_s2,
             self.  lmin_s2,
             self.  lmax_s2))

**Comment by jacg** [comment]
The symmetry of

    if self.plot_s1:
        pf.scan_S12(S1)
    if self.plot_s2:
        pf.scan_S12(S2)

is more apparent if you write it as

    if self.plot_s1: pf.scan_S12(S1)
    if self.plot_s2: pf.scan_S12(S2)

**Comment by jacg** [comment]
This is an interesting case

    mpl.plot_sipm(sipmrwf[evt],
                  nmin =  0,
                  nmax = 16,
                  x=4,
                  y=4)

Although
    
    mpl.plot_sipm(sipmrwf[evt],
                  nmin =  0,
                  nmax = 16,
                  x    =  4,
                  y    =  4)

seems to be more in line with JCK-1, I think I prefer the former:
it highlights related variable groups better. But I would
probably put whitespace around the `=`.

    mpl.plot_sipm(sipmrwf[evt],
                  nmin =  0,
                  nmax = 16,
                  x = 4,
                  y = 4)

**Comment by jacg** [comment]
Rewriting

    S2Si = pf.sipm_S2_dict(SIPM,
                           S2,
                           thr = self.thr_sipm_s2)

as

    S2Si = pf.sipm_S2_dict(SIPM, S2,
                           thr = self.thr_sipm_s2)

saves a line, and probably doesn't lose too much in readability.

**Comment by jacg** [comment]
The line-continuing `\` is superfluous, and the `format` should
be algined with the string in the above line, aaaand the dot is
probably better on the second line, in

    print('event in file = {}, total = {}'.\
      format(evt, n_events_tot))

so I'd write it as

    print('event in file = {}, total = {}'
          .format(evt, n_events_tot))

**Comment by jacg** [comment]
The above comments contain some material that might be included in #80.

**Comment by jjgomezcadenas** [comment]
Will you prepare a PR with all the above changes (they are all fine as far as I am concerned)

**Comment by jacg** [comment]
See #82.

**Pull request merged**
