### PR TITLE
Apply range selection to errors in fit function

### PR DESCRIPTION
**Pull request by gonzaponte**

### CODE REVIEW

**Review by jjgomezcadenas — DISMISSED** [review]
Necessary addition (fitting without errors not really fitting) with a test.

**Comment by gonzaponte** [comment]
I have moved the test to a more natural place within the file and parametrized it to cover another case.

**Comment by jacg** [comment]
Errrm ...

> Merge branch 'master' into fiterrorsrange

Why are you making spaghetti?

**Comment by gonzaponte** [comment]
I have accidentally pushed the "update branch" button. But I have already fixed it.

**Pull request merged**
