### PR TITLE
Combine status codes of parallel and serial test runs

### PR DESCRIPTION
**Pull request by jacg**
Travis was spuriously reporting success when parallel tests
failed. This is because the serial tests follow the parallel ones in
`run_tests_par` and their success was treated as the overall success,
overriding any failure that might have occurred in the parallel ones..

### CODE REVIEW

**Comment by jacg** [comment]
@jmbenlloch Could you please have a look at this?

**Review by jjgomezcadenas — APPROVED** [review]
Obvious and needed

**Comment by jjgomezcadenas** [comment]
@jacg do you want to update this branch and merge it?

**Comment by jacg** [comment]
I'm waiting for @jmbenlloch to look at it.

**Pull request merged**
