### PR TITLE
Cities description

### PR DESCRIPTION
**Pull request by gonzaponte**
Add a description to each city.

This is rebased on top of #565 so only the last commits are relevant.

### CODE REVIEW

**Comment by jacg** [comment]
Can't this go on top of #548?

**Comment by jacg** [comment]
And given that it doesn't touch any code, its branch name should start with `docs.` in order not to waste time on Travis.

**Comment by gonzaponte** [comment]
> Can't this go on top of #548?

It can, but I thought it would be handier to do it after the renaming.

> And given that it doesn't touch any code, its branch name should start with docs. in order not to waste time on Travis.

I forgot about this. I think I can't rename the branch without killing the PR, so it is probably better to keep it and remember it next time.

**Comment by jacg** [comment]
We're stuck with this branch name, and I don't think it's worthwhile opening a new PR just for that.

**Review by andLaing — CHANGES_REQUESTED** [review]
An Important  step in making the functionality of the cities clear to new and inexperienced users.
With the descriptions added it is now possible to understand what each city does and where it lives in the data processing chain. While the city names are arbitrary and void of any use or character (literary or otherwise) changes to meaningful names have been rejected by the management for reason unexplained in any coherent manner.

There are some description errors or clarifications which I have in my local version, I need push permission to send them to the PR or I can send a text copy if preferred.

**Comment by gonzaponte** [comment]
@jacg @jmbenlloch It seems @andLaing cannot push here. Is it a matter of permissions in IC?

**Comment by paolafer** [comment]
This afternoon I've been problems pushing to my nexus fork in Gitlab, maybe it's a global issue?

**Comment by jmbenlloch** [comment]
Can you copy here the errors you are getting?

**Comment by andLaing** [comment]
Pushing to https://github.com/gonzaponte/IC.git
remote: Permission to gonzaponte/IC.git denied to andLaing.
fatal: unable to access 'https://github.com/gonzaponte/IC.git/': The requested URL returned error: 403

I get the same error (with and without -f) for any branch on @gonzaponte 's github, we tried yesterday with an empty one.

**Comment by jmbenlloch** [comment]
@andLaing can you try again now?

In general you can not push to any branch on @gonzaponte 's fork. You would need write permissions on his fork to do that. Branches from PRs are different, you should be able to do that since PRs are thought for that kind of collaboration. I have changed your permissions on nextic/IC, you had "read" and now you have "write". I think it should work now.

**Comment by andLaing** [comment]
Seems to have worked, thanks @jmbenlloch

**Comment by andLaing** [comment]
The tests seem to be failing on something related to liquid cities.
Probably will be sorted once rebased, I'll approve so that you can get on with all the rebasing etc

**Review by andLaing — APPROVED** [review]

**Comment by gonzaponte** [comment]
Waiting for #565

**Comment by andLaing** [comment]
@paolafer , why only for Penthesilea?

**Comment by paolafer** [comment]
Because it's the first one I found. If you approve the idea, I can do it for each one of them.

**Comment by jjgomezcadenas** [comment]
Please do!

**Comment by paolafer** [comment]
I would also propose to use the original names of the cities (meaning, the Italian ones), instead of the English translation. I think that they sounds evocative even to English speakers, and we are already pronouncing them as if they were Italian, anyway (for instance, Irene, Penthesilea...).
Only a few changes would be needed, namely:

Dorothea --> Dorotea.
Penthesilea --> Pentesilea.
Phyllis --> Fillide.

Opinions?

**Comment by andLaing** [comment]
If there are any more name changes they should be to meaningful names not Italian versions of the existing ones. Changing the names in this case just gives more work to change all the scripts etc which call them.

They are currently 0% evocative, moving to the Italian versions is a 0% change in this subjectiveness and adds work, so I vote no.

**Comment by paolafer** [comment]
I’m not going to enter the discussion about using city names. Starting from the fact that we’re doing that and it’s not going to change, I just thought it was more meaningful to use the original ones.
As for the extra work, it shouldn’t be really much, just a matter of find & replace (but I could be wrong here). 
Anyway, it is just an idea.

**Comment by jjgomezcadenas** [comment]
The choice of giving the main programs transforming the data in IC the qualifying of "cities" and the name of specific cities was done-by-design and certainly I stick to it, but I believe it can be argued that Pentesilea or Dorotea are  are actually **easier** to remember that CalibSiPmWithPMts for example. They are certainly evocative and most people seem to like it. So, let's please, please close the discussion here. Cities are cities, and the names of the cities are going to be those from "Invisible Cities".  This is not a "management decision", but a "design decision". It didn't come from some random manager, but from the guy(s) who designed (and mostly implemented) the software. 

This said, I propose that we leave the current names of cities as they are, and suggest that we consider the original Italian names for future cities.

**Comment by paolafer** [comment]
I’m ok with that, Juanjo.
However, could we at least change Phyllis, which hasn’t been implemented yet 😁?

**Comment by paolafer** [comment]
Nevermind, I just realized that Phyllis has been implemented already (I must had in mind some previous version of the code...)

**Comment by andLaing** [comment]
@jjgomezcadenas , I had no illusion that there was going to be a change but if this is truly a place for discussion: changing names without thought (and randomly choosing names from a book is not thought) is pointless. All aspects should be mentioned.

> I believe it can be argued that Pentesilea or Dorotea are are actually easier to remember that CalibSiPmWithPMts for example

Of course if you choose the most random name without thinking about it you could argue that what you have is better but manipulative political digital absolutism isn't really in the spirit of software development nor science.

> They are certainly evocative

Of what? If you've read the book it maybe reminds you of a nice passage or something but evocative of anything related to what we're doing? As I've said before, if it has no meaning here it's just pretentious and confusing.

> This is not a "management decision", but a "design decision"

Let's be honest now @jjgomezcadenas , this was your decision, you like it because you like the book and you get upset when it's pointed out that it adds nothing objectively or subjectively which is why I enjoy poking fun at it so much 😄

**Comment by jjgomezcadenas** [comment]
Yes, yes, YES. Such is life and bosses do as they please. Get over it and move on to the next level of Karma. :)

**Comment by gonzaponte** [comment]
Is there anything left in this PR or can we merge it?

**Comment by gonzaponte** [comment]
I'll take the silence as a no and merge this as soon as travis finishes.

**Pull request merged**
