### PR TITLE
SiPM pdf generation functions

### PR DESCRIPTION
**Pull request by andLaing**
Implements a 'city' to generate pdfs for the SiPMs

### CODE REVIEW

**Comment by jacg** [comment]
Welcome @andLaing !

While I haven't got the time right now to look at this in detail, and others will be better qualified to address the physics side of things, I have a few comments about the way we do things in IC that make life easier in the long run:

+ Please do development on feature branches rather than `master`
+ We do not admit merge commits, except to merge accepted PRs into `nextic/master` once they have been rebased. This means that, in order to get the latest developments on `nextic/master` into your branch, you should
   1. fetch (**not pull**) `nextic/master` into your local clone
   2. *rebase* your branch on top of it, rather than merging `nextic/master' into your branch or vice-versa.
+ Please wrap commit messages at around 72 characters: many places where such messages might be viewed, don't deal with long lines very well.
+ Configuring your editor to remove trailing whitespace helps to avoid distracting entries in the diffs.

This PR is on your `master` branch, which is likely to confuse reviewers who will try to fetch it in order to take it for a spin. Unfortunately GitHub PRs are tied to the branches on which they are started, so I think it would be best if we close this PR and re-open a new one on a feature branch. I propose that you do this by

1. putting a new branch on 7da5fb1f (the last commit before the merge commit),
2. fetching the current `nextic/master`,
3. rebasing the former on the latter,
4. opening the new PR on your new branch.

If you are unfamiliar with the mechanics of any of these operations, there should be plenty of local IC-ists eager could help you.

**Comment by jacg** [comment]
Sorry, it seems that I missed a detail about the topology of your PR, and that linearizing it by following the steps I propose above, is not going to work.

I'll see what I can do from here, and try to give you a cleaned up branch that you can submit.

**Comment by jacg** [comment]
Another quite important point: the first line of commit messages (that's the title) should be no longer than 60 characters, preferably 50, and it **must be followed by at least one blank line separating it from the rest of the commit message**.

**Comment by andLaing** [comment]
ok, cheers. I'll read through all this in detail when I can.

Just one comment, I did the moving into my local master to do the pull
request because that's what the guide in docs/contributing.rst says to do.
Otherwise I would have had no idea rather than very little.

Andrew

**Comment by jacg** [comment]
> I'll read through all this in detail when I can.

No worries.

> Just one comment, I did the moving into my local master to do the pull request because that's what the guide in docs/contributing.rst says to do.

I appreciate that that document hasn't been updated for a long time, so I apologize for any inaccuracies therein. A quick glance reveals some obvious problems. I'll try to fix them ASAP.

**Comment by jacg** [comment]
@andLaing I have prepared a clean branch with what should be identical content to what you submitted, but rebased on top of recent `nextic/master`, with the merge commit removed, and with sanitized commit message, [here](https://github.com/jacg/IC/tree/sipm-pdf). Please check that it looks like what you intended, and then it would probably be best if you created a new PR off that branch (closing this one).

The procedure would be:

1. add my fork as a remote,
2. fetch the branch into your local repo,
3. place your own branch on top of it,
4. push it to your fork
5. create the PR.

Don't hesitate to ask for help, if needed.

**Comment by andLaing** [comment]
Hi

I’ve had a look at what you’ve written, thanks for that. I’ve noticed that another change from another branch I was working on has snuck in. This is probably a product of the general bad practice of merging probably.

I still have my branch where I did the development for this, would you recommend doing the changes there and starting from scratch or should I do as you’ve recommended from your fork?

Cheers

Andrew

**Comment by jacg** [comment]
> would you recommend doing the changes there and starting from scratch or should I do as you’ve recommended from your fork?

Difficult for me to say from here. Do whatever is simplest and easiest for you. I created the branch just as a convenience for you: if it contains changes that you don't want to submit, and it's easier for you to start from elsewhere, that's absolutely fine. Don't feel under any obligation to use my branch.

If you want to remove stuff from my branch, one way to do that would be to

+ check out my branch
+ edit the files to remove the stuff you don't want
+ run tests to make sure everything looks ok
+ *amend* the commit

An alternative for the last step is to make a plain commit, and later squash it into the previous one. In the long run, both of these approaches end up having the same effect. If you haven't done these things before, it's best to get someone local to show you how to do it. It's not difficult, but you will save a lot of time if someone shows you the ropes.

But as I said, no obligation to use my branch at all. Feel free to start from scratch on your own branch, if that seems simpler. You don't even really need to rebase before making the PR. *Someone* will have to do it before merging, but you don't need to concern yourself with that at this stage.

**Pull request closed without merging**
