### PR TITLE
Small fixes in fit functions

### PR DESCRIPTION
**Pull request by bpalmeiro**
These are just small changes that remained from PR #359:
    - Some Cosmetics.
    - Removing a non-zero selection in fit function, no longer necessary.
    - Adding a test that demonstrates that invalid values for sigma were accepted.
    - Correcting correspondingly the code for checking invalid values in sigma.

### CODE REVIEW

**Comment by jahernando** [comment]
The PR fix an issue with the fit functions related of how to handle the fit when the client provides null errores. If this case happens, now the function throws an exception. The PR incorporates a test. 

If will be nice to incorporate a comment in the doc-string suggesting the user to provide Poisson's errors when using histogram contents for the fit.

**Review by jahernando — APPROVED** [review]
The PR solves an issue related with the treatment of the data when the user sends null errors to the fit function. Now it raises an exception.

The PR includes a test.

**Comment by bpalmeiro** [comment]
We should clean the commit history and some cosmetics before merging

**Comment by bpalmeiro** [comment]
Done! It's ready to be "approved " and merged.

**Comment by gonzaponte** [comment]
@jahernando, please check that you're still happy with this PR so it can be merged.

**Comment by jahernando** [comment]
Yes, please merge, I understood that you do the merge!

**Pull request merged**
