### PR TITLE
Write run info & evt number in Diomira

### PR DESCRIPTION
**Pull request by jmbenlloch**
Diomira writes run rumber in one table and event number+timestamp in
another table. There is a new option for configuration files (or
command line) to specify which number should be assigned to the first
event in the file.

This is useful for MC productions where we want to keep an absolute
numbering for all the events in one MC run.

This PR addresses #145

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
I cannot manage to see where you call set_output_store()

**Comment by jjgomezcadenas** [comment]
@jacg This is the PR that addresses the comments "COMING SOON" in IRENE. It extends DIOMIRA (which produces MC events) so that it also writes a table with absolute event numbers, etc., so that we can treat data and MC in an uniform way.

**Comment by jacg** [comment]
> I cannot manage to see where you call set_output_store()

Line 101 in `diomira.py` ?

**Comment by jjgomezcadenas** [comment]
Concerning your text:    
                 
                       # add evt number
                        evt_row = self.evtsInfot.row
                        evt_row['evt_number'] = evt + self.first_evt
                        evt_row['timestamp'] = 0
                        evt_row.append()

This could go to the base class, no? 

Then

                        n_events_tot +=1
                        if n_events_tot % self.nprint == 0:
                            print('event in file = {}, total = {}'
                                  .format(evt, n_events_tot))

In the branch pmaps-writer I have included a small function print_conditional in the base class (City), this would save a few lines of code.

**Review by jjgomezcadenas — COMMENTED** [review]
Aside of the small comments I have done, my limited eyes cannot see much wrong here either. From my side this can go, after @jacg is happy (which means he approves).

**Comment by jmbenlloch** [comment]
> This could go to the base class, no?

I don't see why that code should go to the base class. I understand that in MC we start at Diomira where we generate the event number. In data there is already a event number from DAQ. Following cities, both in MC and data, should copy the event number that is already in the file, not compute a new one. To propagate the event number we need a different code.

**Comment by jjgomezcadenas** [comment]
But Diomira is derived from a base class (SensorResponseCity). Should the code go there?

**Comment by jmbenlloch** [comment]
There are 3 pieces here:

1- **Create tables**. This is done in `set_output_store`
2- **Write run number**. Done in the run method after opening output file.
3- **Write event number & timestamp**. Also done within `run` method.

Steps 2 and 3 need step 1 to be executed before. Since all the output is managed within Diomira I don't see why we should put 2 or 3 in `SensorResponseCity`, it is just another Diomira output.

Besides that, if you want to encapsulate those 4 lines in one function it is done in my last commit. Feel free to choose any alternative, I don't have strong feelings about it.

**Review by jacg — APPROVED** [review]
I won't have time to look into this deeply before I disappear. Superficially, I see nothing wrong. I don't want to delay this any longer, so I'm approving and merging ...

**Pull request merged**
