### PR TITLE
Adds new fields for corrected charge and energy to Hit and Cluster

### PR DESCRIPTION
**Pull request by jerenner**
This pull request creates four new fields, two in class `Hit` and two in class `Cluster`:

- `Ql`: lifetime-corrected charge
- `El`: lifetime-corrected energy
- `Qc`: fully-corrected charge (lifetime + x,y)
- `Ec`: fully-corrected energy (lifetime + x,y)

The field `Ql` and `Qc` are added to the `Cluster` class, and the fields `El` and `Ec` are added to the `Hit` class.  These fields are automatically initialized to -1 if not specified and are intended to be filled later when corrections are made.

### CODE REVIEW

**Review by jjgomezcadenas — COMMENTED** [review]
A straight forward change needed to implement Thekla. Please add one more field, Zc (corrected Z, which we do also at Thekla level, knowing drift velocity).

**Comment by jjgomezcadenas** [comment]
Review in progress (@jjgomezcadenas). Please @jerenner solve conflict, check tests, and add missing field

**Review by jjgomezcadenas — APPROVED** [review]
The new fields are needed and tests show functionality. Please @carmenromo merge.

**Comment by jacg** [comment]
Go for it @carmenromo, this is a real live one!

@jmbenlloch Could you please walk @carmenromo through this: she'll need write access for the last step.

**Comment by jmbenlloch** [comment]
> @jmbenlloch Could you please walk @carmenromo through this: she'll need write access for the last step.

I'm in Canfranc now, but I guess we can try tomorrow via skype.

**Comment by jacg** [comment]
> I'm in Canfranc now, but I guess we can try tomorrow via skype.

Is there anyone in physical proximity to @carmenromo who is familiar with the procedure? @paolafer has merged a PR before, or is that a figment of my imagination?

**Comment by jmbenlloch** [comment]
> Is there anyone in physical proximity to @carmenromo who is familiar with the procedure?

If this is not urgent I can help @carmenromo on Tuesday, I'll be back at IFIC by then.

**Comment by paolafer** [comment]
I have merged a PR before, yes, but it was long time ago. It is probably wiser to have José María instructing Carmen.

**Comment by jacg** [comment]
> If this is not urgent I can help @carmenromo on Tuesday, I'll be back at IFIC by then.

It's semi-urgent. The whole point of giving @carmenromo the merger role, is to eliminate the backlog of approved but unmerged PRs, which accumulate massive technical debt by requiring increasingly difficult conflict resolutions. There's already one item in the queue, and I see another two appearing in the very short term ... and if the backlog is growing because the merger doesn't know how to merge, that's very counterproductive. I (or you) could merge it, but then poor @carmenromo misses out on another few opportunities to learn how to do it ... and thus the cycle continues.

@carmenromo seems very keen to get started (and the projects needs the role to be filled), so I suggest that we supply whatever help we can as soon as possible, even if it's remotely. If it works, great; if not, we'll have to do it when you get back.

**Comment by carmenromo** [comment]
ok @jacg, @jmbenlloch, we can do it tomorrow remotely

**Comment by jmbenlloch** [comment]
Ok, I will call @carmenromo tomorrow morning.

**Pull request merged**
