### PR TITLE
Issue149

### PR DESCRIPTION
**Pull request by gonzaponte**
Fix issue #149. The function cdf_to_dict in pmaps_functions_c.pyx has been restructured so it does not include unexisting events.

### CODE REVIEW

**Comment by gonzaponte** [comment]
I still have the squash pending.

**Review by jjgomezcadenas — COMMENTED** [review]
Would it be possible to  benchmark your current function and compare it wit the old one?

**Comment by gonzaponte** [comment]
What do you mean?

**Comment by jacg** [comment]
I have included two commits. The first one uses `xxx` as the implementation of `df_to_pmaps_dict`. The second one replaces that implementation with `yyy`. I would like to keep them both, as this will be the only record remaining of `xxx` once I have cleaned up my local branches.

The namedtuple used to store the pair of time and energy arrays is called `Peak`. Any better suggestions?

**Comment by jacg** [comment]
We have just noticed that the `df_to_pmaps_dict` tests do not exercise the namedtuple within, and that the namedtuple is not being used at all in the first commit. Fixes coming up ...

**Comment by gonzaponte** [comment]
> The namedtuple used to store the pair of time and energy arrays is called Peak. Any better suggestions?

Waveform?

**Comment by jjgomezcadenas** [comment]
Peak is correct. We want to keep the name Waveform for the whole thing. A Waveform contain a number of Peaks…

**Comment by jacg** [comment]
We just have some doubts about `test_df_to_pmaps_dict_limit_events`: It asks for a maximum of 10 events, and then asserts that there are 4. I understand how this fits with the data presented in the test, but it smells fishy. Is this really what we mean/want?

**Comment by gonzaponte** [comment]
After taking directly, we've concluded that this ***is*** what we want

**Comment by jacg** [comment]
We have removed the comment which expressed our doubts, from the test.

As far as we are concerned, this is now ready.

**Comment by jjgomezcadenas** [comment]
PR coming then?

**Comment by jacg** [comment]
This *is* a PR.

(If you did all this via GitHub, rather than your mail, all these things would be obvious ... which is a topic for another discussion that we need to have sometime, but not here)

**Comment by jjgomezcadenas** [comment]
Sorry! Just got sidetracked. Review coming

**Review by jjgomezcadenas — COMMENTED** [review]
Quite impressive. I have only a suggestion, for your consideration. I believe that the "normal user" (whoever this guy is) should work always with the "dictionary" PMAPS, and never with the "DF" PMAPS. This is to avoid proliferation of PMAPS analysis code based in two different data structures. In short, I see "DF" as internal representation of the PMAPS (a mapping of the potables in file) and "dictionaries" as the "analysis" representation. 

If this is agreed, I believe that read_pmaps() should return directly the dictionaries, thus, load the DF functions, then call the df_to_pmaps_dict(). 

This, BTW, may bring an interesting argument in favour of implementing a class PMapsReader(), as a convenient way to hide functions that we do not want to expose publicly. In this case I would consider df_to_pmaps private to the class while read_pmaps would be public. 

In any case, no need to address the PMapsReader now, just consider that read_pmaps() could return the dictionaries straight away.  Let me know what you think (implement change if you agree) and then I will approve the PR

**Comment by jacg** [comment]
> If this is agreed, I believe that read_pmaps() should return directly the dictionaries, thus, load the DF functions, then call the df_to_pmaps_dict().

Yes, we were just making similar observations here.

Shall we do it now, or as a separate PR?

**Comment by gonzaponte** [comment]
> If this is agreed, I believe that read_pmaps() should return directly the dictionaries, thus, load the DF functions, then call the df_to_pmaps_dict().

The problem is that the SiPMs need a different function (and read_pmaps returns them as well). I am working on the implementation of "s2sidf_to_dict" on a different branch.

> Shall we do it now, or as a separate PR?

Because of what I've just said, it should be implemented in a separate PR.

**Comment by jacg** [comment]
Then all that remains in this PR is approval and merging.

**Comment by jacg** [comment]
No, one more thing. Elsewhere @gonzaponte says

> >      I suggest df_to_pmaps_dict as the new name

> Since it is already in pmaps_functions.py, I would avoid naming it pmaps (simply df_to_dict?).

I like this idea. Shall we make the change?

**Comment by jjgomezcadenas** [comment]
I like the current name is expressive and clear

Enviado desde mi iPhone

**Comment by jacg** [comment]
The version with the name changed is available in *my* fork (branch name: issue149). I have left it out of this PR so far.

**Review by jjgomezcadenas — APPROVED** [review]

**Pull request merged**
