### PR TITLE
delete correct_s1_ene from base_cities

### PR DESCRIPTION
**Pull request by abotas**
delete the line in PmapCity.pmaps that does not do anything!

### CODE REVIEW

**Review by jjgomezcadenas — APPROVED** [review]
good catch

**Comment by jacg** [comment]
What's that merge commit doing there?

**Comment by jjgomezcadenas** [comment]
My mistake, pushed the wrong buttom

**Comment by jacg** [comment]
I trust that it won't find its way into `master`!

**Comment by jjgomezcadenas** [comment]
Not if you tell us how to undo the mistake (or if you kindly fix it).

**Comment by jacg** [comment]
Give a man a fish ...

In your local repo, reset the branch to the commit *before* the merge, then force push (with lease, if it was you who pushed it, without lease if it was someone else: which is why it should, preferably, be done by the person who pushed it in the first place).

(I thought we had this particular fishing technique mastered.)

**Comment by jjgomezcadenas** [comment]
OK, @abotas can you fish this, please?

**Pull request merged**
