### PR TITLE
Issue174

### PR DESCRIPTION
**Pull request by gonzaponte**
There was some mismatching between the number of slices in the cathode and in the anode. This was caused by a difference in the time value of consecutive slices smaller than one mus. Although this is still the case, the number of slices has been forced to be the same in both planes.

These changes require rerunning irene.

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
how big is your pmaps file?

**Comment by gonzaponte** [comment]
204k

**Review by jjgomezcadenas — APPROVED** [review]
As agreed, this fix provides a practical solution to the problem of unmatched slices.

**Comment by gonzaponte** [comment]
I will squash it, then

**Comment by jjgomezcadenas** [comment]
I have approved the PR, but I believe we should squash. Will you do it?

**Comment by gonzaponte** [comment]
Done.

**Pull request merged**
