### PR TITLE
Add functions to read back corrections tables

### PR DESCRIPTION
**Pull request by gonzaponte**

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
Can you provide a test?

**Review by jjgomezcadenas — APPROVED** [review]
We need these functions and I can't see anything wrong with them, so I am approving them, but please try and add a test.

**Comment by jjgomezcadenas** [comment]
Why are tests failing now @gonzaponte ? That should not be the case (was not last time I looked, I think
)

**Comment by gonzaponte** [comment]
The test is there and it does not fail. The failure comes from another (unrelated) test that is not properly tuned with flaky. As a matter of fact, I opened PR #241 to fix it.

**Pull request merged**
