### PR TITLE
Added protection for rebin bin time

### PR DESCRIPTION
**Pull request by andLaing**
Only uses positive charge for
weighting to avoid non-sequential
bins.

### CODE REVIEW

**Review by gonzaponte — APPROVED** [review]
Perfect! Good way to get rid of the negative weights that were messing up the order of the time bins.

**Comment by gonzaponte** [comment]
Are you sure about this last commit? I don't think there is a huge difference in any case, but at first glance, the previous option seems less invasive, meaning that you only do something when it is actually needed.

**Comment by andLaing** [comment]
Yes, sorry. I realised after the push that it was wrong and undid it. We're seeing some fail paths though due to an issue with the deconv and/or the selection of the peaks. I'mm looking at protections but I think it's a wider issue that should be addressed so I'll put an issue

**Comment by andLaing** [comment]
I'm going to close this pull request as we found some failures in high statistics testing.

The changes plus additional protections are revisited in PR #683

**Pull request closed without merging**
