### PR TITLE
Fix sipm ids and charges in slice

### PR DESCRIPTION
**Pull request by Aretno**
Deleted the function as suggested in https://github.com/nextic/IC/pull/297 

(I don't know if the previous PR could be edited with the new commit, sorry)

### CODE REVIEW

**Comment by jacg** [comment]
It can be edited, but the simplest thing to do is to add a comment in the old PR, saying that the function is being deleted here.

An even cleaner thing would have been to re-open the previous PR (rather than starting a new one) and remove the function there.

**Comment by jjgomezcadenas** [comment]
Actually, I am a bit uneasy about deleting the function, rather than fixing it. Notice that we were stating explicitely that the funciton was not in the API (as the name _xxx indicates). So far we have been consistently keeping private versions of the python function whenever we had a cython public function. The python function have often been used to cross check the cython counterpart. 

In this case the function is so simple that it is really not worth, but I am not 100 % sure that I want to break the habit of having a python function for each cython function.

Although perhaps the best thing would be to delete *all* the python functions that are superseded by cython counterparts and not explicitly used in tests...

**Comment by jacg** [comment]
The fundamental point is, that we should not have untested functions in our code base. And we *definitely* do not want broken functions in our code base. Now, whether you fix this problem by adding tests, or by removing functions is a second order issue.

Remember: having a function which does not get tested automatically and regularly, is equivalent to saying "I do not care if this function is broken". If you don't care if a function is broken, what is it doing in your code base?

I think that duplication of functions is downright counterproductive. There are arguments for keeping simple and clean pure-python versions of functions which have been superseded by uglier, optimized Cython versions. But the job of 'keeping' them is up to the version control system: the functions are still there in our VCS, should we ever need them, but they shouldn't be polluting the active code base.

My vote is to remove all superseded python versions

> The python function have often been used to cross check the cython counterpart.

The function has to pass the tests. You develop a slow first version of the function, you write a thorough test suite for it, then you write an optimized version of the function, and ensure that it still passes the same tests. Once it does, what is the point of keeping the old version? How does it help to cross check? (Is this perhaps some instinct that you developed in the bad old days when you didn't have automatic test suites?)

Given that this is not the first time that one of these obsolete Python functions causes confusion, supports my point. Let's get rid of them all.

**Review by jjgomezcadenas — APPROVED** [review]
Following the advise of the Master I hereby approve removing this obsolete function and vouch to keep removing all the others. Amen.

**Comment by jjgomezcadenas** [comment]
@aretno please rebase your branch to main (ask @gonzaponte or @abotas if trouble), then one of them, please merge!

**Pull request merged**
