### PR TITLE
Threshold rebin

### PR DESCRIPTION
**Pull request by andLaing**
A new rebinning function based on a minimum
number of photo-electrons in the sum of the
pmts.

Shouldn't be approved before #593 since there
is likely clashes.

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
@andLaing do you want me to review this PR? If so, please rebase

**Comment by andLaing** [comment]
That'd be great. just pushed a rebased version

**Comment by andLaing** [comment]
Now rebased on the last merge with #593 with all clashes removed

**Review by jjgomezcadenas — APPROVED** [review]
A new method to rebin S2 based in charge threshold, rather than in a fix time interval. It offers the appealing advantage of virtually eliminating the zero-charge slices, which appear in fix-time-bin methods. The method is extensively tested.

**Pull request merged**
