### PR TITLE
Sphinx example setup

### PR DESCRIPTION
**Pull request by jmbenlloch**
Test setup to solve issue #46

### CODE REVIEW

**Comment by jacg** [comment]
I think we agreed that

- This is still work in progress
- The branch name sould be changed to `docs.sphinx`
- The docs directory should be changed from `docs` to `doc`

**Comment by jmbenlloch** [comment]
Several things:

* `docs` folder is renamed to `doc`
* A Makefile is added. 

With the Makefile, to compile html one can just run:

`make html`

Without the Makefile sphinx-build is needed. It can be executed like this:

`sphinx-build -b html doc doc/build`

I think it is convenient to have the Makefile (specially if we want to add a more general one in the future #88)

And for last, I don't know how to rename the branch in github, I have tried doing it first locally and the pushing to the repository, but it didn't work. After a search on google, people suggest removing the old branch in github and pushing again the branch with the new name. I don't know what would happend with the already existing pull requests. Therefore, I have not updated the branch name.

**Comment by jacg** [comment]
I think that the PR is coupled to the branch name, so changing the name essentially means closing the PR.

If we are still considering this work in progress, then it's

- no problem to close the PR,
- a good idea to rename the branch (to something starting with `docs.`), in orded to avoid Travis builds on subsequent pushes that are sure to come.

**Review by jjgomezcadenas — COMMENTED** [review]
I have run the makefile and the html pages are correctly produced (once you install sphinx). Please add sphinx to  the environment

**Comment by jmbenlloch** [comment]
I have added sphinx to the environment in manage.sh and also `doc/build` in `.gitignore`. It has been tested on a fresh installation and it works well.

**Review by jjgomezcadenas — APPROVED** [review]
The system works in two independent computers (my *fast* Mac and the *slow* linux new laptop).

**Pull request merged**
