### PR TITLE
Add maximum charge variable

### PR DESCRIPTION
**Pull request by gondiaz**
This PR adds maximum charge (qmax) variable in DST tables, therefore it modifies both dorothea and penthesilea files.

### CODE REVIEW

**Comment by jacg** [comment]
The tests are failing for reasons which I don't recognize as being the typical spurious ones. In fact, it looks rather likely that this PR has broken some existing tests.

**Comment by jacg** [comment]
Please rebase on top of #783 as soon as it is merged, so that we get clearer test reporting on GHAs.

**Comment by jacg** [comment]
#783 has been merged. Please rebase.

**Review by jerenner — APPROVED** [review]
Adds qmax, the maximum SiPM charge observed for each S2 peak, to the DST. Tests pass - approved.

**Pull request merged**
