### PR TITLE
Translate emacs init file from el-get to use-package

### LINKED ISSUE #401: Magit installation doesn't work with Mac
Using the init.el script provided in nextic/docs I get the following errors.
```
fatal: destination path 'el-get' already exists and is not an empty directory.
```

I can't find where it is installed (it's not in .emacs.d/)

Additionally, I get the errors:
```
Warning (el-get): Your Emacs doesn't support HTTPS (TLS).
Warning (initialization): An error occurred while loading ‘/Users/laingAndrew/.emacs.d/init.el’:

error: Couldn’t clone el-get from the Git repository: https://github.com/dimitri/el-get.git

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Mac and aquamacs info:

Mac OSX 10.12.6

Aquamacs 3.3  GNU Emacs 25.1.1

Any ideas? José María and I are not having any success solving the problem so far.

### PR DESCRIPTION
**Pull request by jacg**
el-get was getting rather flaky down the years. use-package seems much more stable.

Closes #401

### CODE REVIEW

**Comment by jacg** [comment]
As this seems to have solved #401, could someone please approve it?

**Review by jjgomezcadenas — APPROVED** [review]
Indeed, solves #401

**Comment by jacg** [comment]
@gonzaponte Are you merging this right now?

**Comment by gonzaponte** [comment]
Yes, I am. I am just waiting for Travis to complete.

**Comment by jacg** [comment]
Yes, I was bloody confused for a while, because so was I. Note that the new merge commit policy is to drop the space and hash at the beginning of the title ... which my version of the commit (which is currently the only one, it seems) does. So please make sure you take that version. I'll let you finish it off.

**Comment by gonzaponte** [comment]
Ok. I had pushed also a reword to comply with the new merge commit policy. I think everything is coherent now.

**Pull request merged**
