### PR TITLE
Nullify waveforms of masked sensors

### PR DESCRIPTION
**Pull request by gonzaponte**
Mask sensors in the code. We removed it somehow from the code.

### CODE REVIEW

**Comment by paolafer** [comment]
Hi Gonzalo! I'm a bit confused about this. When was the masking code removed? We had to modify the corona algorithm to take into account masked channels, and I think we tested it with the whole code, right?

**Comment by gonzaponte** [comment]
> When was the masking code removed?
I don't know...

> We had to modify the corona algorithm to take into account masked channels, and I think we tested it with the whole code, right?
Yes, but I've just realized that the changes affect only to the corona algorithm when it is not configured for barycenter.

**Review by jjgomezcadenas — COMMENTED** [review]
This PR kills a monster that has been killed, I think a number of times and then has resurrected. Hopefully it will stay dead from now on.

**Review by jjgomezcadenas — APPROVED** [review]

**Comment by jacg** [comment]
Why was the monster's resurrection not detected by a test?

**Comment by gonzaponte** [comment]
> Why was the monster's resurrection not detected by a test?

I don't think we've paid too much attention to this monster. And I think we had only amputated a few members, but never killed it. It should be dead now.

Now in technical terms:
I think we've never fully masked the dead sensors. My feeling is that we just masked them in some particular scenarios (corona algorithm), but not generally (when corona is configured to perform a barycenter, for instance).
In this PR the waveforms of the masked sensors are nullified (set to 0). This way, they can never be used for anything.

**Comment by gonzaponte** [comment]
By the way, I am aware this whole thing needs a careful review, but we need this now, so we will pay the technical debt later.

**Comment by jacg** [comment]
> I am aware this whole thing needs a careful review, but we need this now, so we will pay the technical debt later.

Fair enough. But I note that we have been taking on a lot of technical debt over the last months, without repaying any: we **really** need to start repaying some of it soon.

I guess that our next sprint should be largely dedicated to repayment of technical debt. Starting with the total liquification of the cities.

**Comment by jjgomezcadenas** [comment]
Agree, we are accumulating TD. Worst, our (expert) man power is dwindling. But yes, agreed, we need to devote the next Sprint to liquify and also to make IC detector-configurable. Among a zillion other things, I guess.

**Pull request merged**
