### PR TITLE
Fix peak width

### PR DESCRIPTION
**Pull request by gonzaponte**
This is a fix to #584.

### CODE REVIEW

**Comment by andLaing** [comment]
This is taking a bit longer than expected as we've discovered that the test data was very out of date (the mc data didn't even have the fix to the simulated PMT gain) so I have to make more extensive changes to the tests than first thought.

**Comment by jjgomezcadenas** [comment]
@gonzaponte, are u done here? Shall we go over it with peras?

**Comment by gonzaponte** [comment]
This is @andLaing's, I don't know the status

**Comment by andLaing** [comment]
> This is @andLaing's, I don't know the status

I think I'm done but someone will have to look at it in detail as there's quite a lot of changes in the tests although the change in the code is small

**Comment by jjgomezcadenas** [comment]
I am out of the picture, unfortunately for this week, I can find time next week. @gonzaponte could you should this?

**Comment by jjgomezcadenas** [comment]
@andLaing can you please rebase? Then I will review

**Review by jjgomezcadenas — APPROVED** [review]
This PR fixes an unpleasant feature,  nice catch. Tests are exhaustive and credible.

**Comment by jjgomezcadenas** [comment]
@andLaing PR approved. @carmenromo please rebase

**Pull request merged**
