### PR TITLE
Adapt IC to new PMAPs model

### LINKED ISSUE #416: Bug in MAU coefficients
As mentioned in #403, the vector of coefficients used in the MAU is full of zeros, which translates to the MAU having no effect at all. The reason for the zeros seems to be an integer division being performed by cython in lines similar to this one:

```
cdef double [:] MAU = np.ones(n_MAU) * (1 / n_MAU)
```

where `n_MAU` is typed as an `int`. I know this happens in my computer, but I don't know whether its universal or not. Thus, I would like to some other people to try this:

- Add the following line to the function `calibrated_pmt_mau` in `reco/calib_sensor_functions.pyx` after the `MAU` vector is created (line 101 in the current master):
```
print("MAU coefficients = ", np.asarray(MAU))
```
- Compile cython code by running `python setup.py develop` in the top directory.
- Run `pytest -s -k test_csum_cwf_close_to_csum_of_calibrated_pmts`.
- Check the output and see whether the `MAU` vector is full of zeros or not. Post your findings in this issue.

The PR adapting the code to the new PMap interface will contain a big refactor of the functions using a mau, so we kinda have already solved this problem, but it would be nice to have some more information and keep this bug in the repo history so we don't forget about it.

### PR DESCRIPTION
**Pull request by gonzaponte**
This PR adapts all existing code in IC to the new PMap interface. This includes a big refactor of `peak_functions`,  `pmap_functions` and `calib_sensor_functions`, which have been fully de-cythonized. The IO functions have also been rewritten to match the new representation.

Everything is thoroughly tested (at least I have tried to do so).

Closes #416

### CODE REVIEW

**Comment by gonzaponte** [comment]
I think I am done fixing stuff. Can someone read carefully the commit history and verify it is understandable and well written?

**Comment by jjgomezcadenas** [comment]
Have you fixed the bug that we discovered while working in the Irene fluxes??

**Comment by gonzaponte** [comment]
Yes

**Review by jjgomezcadenas — COMMENTED** [review]
A titanic & heroic effort. The commit history is clear enough. Congratulations to the authors.

**Review by jjgomezcadenas — APPROVED** [review]
I hereby declare this monumental piece of work approved.

**Comment by jjgomezcadenas** [comment]
Please merge!

**Pull request merged**
