### PR TITLE
Corrections update

### PR DESCRIPTION
**Pull request by gonzaponte**
This PR:
- Adds the normalization by a constant to the class `Correction`.
- Generalizes the class so this new normalization fits better.
- Adds safety checks to the class.
- Provides tests for all of the above.
- Changes the philosophy of correction factors normalization. The normalization now occurs when loading from file, rather than when storing them. The function that reads back the corrections has been modified, accordingly.

### CODE REVIEW

**Review by jahernando — APPROVED** [review]
The commit extends the functionality of Correction class to normalize now to a given value. The normalization strategies and options are now passed by key-arguments.  
Test are modified accordingly. New tests are included to check the normalization to a given value works and to raise exceptions when options of a given normalization strategy are not passed in the key-arguments. 
The PR is approved.
Nevertheless, it seems that the functionality of Corrections when using an interpolation other than 'nearest' is not properly tested. Isn't it?
If not, as it is nor crucial for this release, it is approved, but these tests should be included in a future PR.

**Review by jahernando — COMMENTED** [review]
I approve it again!

**Review by jahernando — APPROVED** [review]

**Review by jahernando — APPROVED** [review]
Approved

**Comment by gonzaponte** [comment]
This PR has been approved by @jahernando, but requires the review of someone with write access.

**Pull request merged**
