### PR TITLE
Fix `test_inverse_cdf_hypothesis_generated`

### PR DESCRIPTION
**Pull request by gonzaponte**
#555 didn't fix all problems.
This will address [the problem](https://github.com/nextic/IC/issues/551#issuecomment-434222203) detailed in #551.

### CODE REVIEW

**Comment by gonzaponte** [comment]
Ok. So the test has passed O(100) travis runs. I think this has been fixed. Please someone review.

**Comment by jjgomezcadenas** [comment]
I see the request for review, but I don't see that I can review, @gonzaponte

**Comment by gonzaponte** [comment]
now?

**Comment by jjgomezcadenas** [comment]
Travelling will approve when i arrive

**Comment by jjgomezcadenas** [comment]
Is says that I am THE reviewer but I cannot find anywhere to add my review...!

**Comment by gonzaponte** [comment]
If you go to the "files changed" tab you should be able to add the review by clicking the green button on the top right.

**Review by jjgomezcadenas — APPROVED** [review]
All is good!

**Pull request merged**
