### PR TITLE
Remove NoSuchNodeError catch in dst loading

### PR DESCRIPTION
**Pull request by gondiaz**
This PR solves issue #800. The proposed solution removes the `NoSuchNodeError` catch in `load_dst` function.

### CODE REVIEW

**Comment by gonzaponte** [comment]
The problem with this function is that it is used both by individual users, which may want just a warning (IIRC, this was the original reason), and the cities, which definitely want to crash if something happens to the file.
Two questions:
1. What should be done with the other exception that is turned into a warning in this very function? It looks like we need to handle that one as well.
2. Have you considered introducing an argument to the function to combine both behaviors? Something in the lines of `ignore_empty`/`unsafe`?

It's been a while since I last had an issue with this function, so other, more frequent users should comment.

**Comment by gondiaz** [comment]
Agree with point 1 that the other warnings should be changed to exceptions, but probably in another dedicated PR.

For point 2: if I understand well the warnings are meant to avoid code breaking in personal analysis notebooks/scripts where the function is used and those people would also be bothered if a new argument is implemented if the default behaviour is to raise an `Exception`. Also the warning message it outputs "not of kdst type" should be changed.

**Comment by gonzaponte** [comment]
> but probably in another dedicated PR.

I don't see the need to open another PR, but I don't have a problem with that.

>  if I understand well the warnings are meant to avoid code breaking in personal analysis notebooks/scripts where the function is used

Yup

> those people would also be bothered if a new argument is implemented if the default behaviour is to raise an Exception.

I'm not sure what you are saying here. The new behavior is going to be to raise an exception in any case, right? Anyone using this function will now have to deal with that anyway. The question is whether to force them to catch the exception explicitly, i.e.
```
try:
    load_dst(...)
except:
    # do something or not
```
or to add an argument to their calls, which is arguably less intrusive
```
load_dst(..., ignore_errors=True)
``` 

BTW, there is a third way: to have `load_dst` to always raise exceptions and define `load_dst_xxx` that handles the exceptions raised by `load_dst`. This is pretty much the same as the adding-a-new-parameter option.

**Comment by gondiaz** [comment]
I agree that adding the extra karg is the less intrusive and probably the best option. `ignore_errrors = False` would be the default and people that uses the function should change to `ignore_errrors = True` if neccessary.

**Review by gonzaponte — APPROVED** [review]
Clear and concise. Approved.

**Pull request merged**
