### PR TITLE
Functions to read and apply corrections using new dataframe format

### PR DESCRIPTION
**Pull request by mmkekic**
The relevant functions to read map and apply geometric and lifetime
corrections are added.

### CODE REVIEW

**Comment by mmkekic** [comment]
I believe that the best thing to so is use the already existing function from krcal in IC and add temporal corrections one. @jjgomezcadenas , @jahernando , @ausonandres , @paolafer , @bpalmeiro  what do you think?

**Comment by jjgomezcadenas** [comment]
I like this stuff. Please add tests!

**Comment by jjgomezcadenas** [comment]
@mmkekic can you add any relevant test and rebase? This can be approved shortly

**Comment by mmkekic** [comment]
I changed the functions to read specific cells of the maps (maps_coefficient_getter) and added some tests to ensure the new functions gives the same result as old (krcalib) one; @jjgomezcadenas  can you give it a look and see if you agree with the new interface? However I would not approve this PR till we add the temporal corrections and Kr scaling, that @ausonandres and @bpalmeiro  are working on.

**Comment by jjgomezcadenas** [comment]
@mmkekic I like the new interface very much. Very elegant and efficient. Good job.

**Comment by jjgomezcadenas** [comment]
Also I like that you removed CorrectionsDF class before I had the change to suggest it!

**Comment by ausonandres** [comment]
You can see here the usage of the new functions and a brief performance of them: 

https://github.com/ausonandres/KrCalibNB/blob/show_new_correction_function/krEvolutionNB/Checking_new_correction_functions.ipynb

**Comment by paolafer** [comment]
@andLaing or @jjgomezcadenas, can you review it?

**Comment by jjgomezcadenas** [comment]
@ausonandres the adress you point too is void, please fix
@paolafer  I will review this, please rebase.

**Comment by bpalmeiro** [comment]
Link corrected and branch rebased

**Comment by jjgomezcadenas** [comment]
@ausonandres I like the NB, but the case is very week, because the corrections are almost negligible. Please find a run with a strong temporal dependence and show that time-corrections make a difference.

**Comment by jjgomezcadenas** [comment]
@ausonandres also, please rebase

**Comment by jjgomezcadenas** [comment]
@Before approving I would like to see a NB running over a run with a strong time variation (e.g, after a spark) and check how the time-dependent-corrections improve resolution.

**Comment by ausonandres** [comment]
Well, I am working on it, so as soon as possible I will upload a new NB. In any case, the temporal correction is optional, so it is easy not to use it.

**Comment by ausonandres** [comment]
As you requested, in this notebook it can be seen how time evolution correction works when e0 changes significantly:
https://github.com/ausonandres/KrCalibNB/blob/show_new_correction_function/krEvolutionNB/Checking_new_correction_functions-time.ipynb

**Review by jjgomezcadenas — APPROVED** [review]
An extensive suite, that imports and improves the capabilities built in ICAROS. After we merge this PR I will apply correction functions directly from IC, and once tested will remove them from ICAROS. 

The suite comes with extensive testing and the NB is very clear and convincing. Good job.

**Comment by jjgomezcadenas** [comment]
@carmenromo @bpalmeiro please merge

**Pull request merged**
