### PR TITLE
Copy MCTracks table in Diomira and Irene

### PR DESCRIPTION
**Pull request by jmbenlloch**
Input files for Diomira (MCRD's) have a table `/MC/MCTracks` with the MC truth information. Diomira is not saving this table in the RWF output file. Obviously, Irene does not have this data either.

We need to have this table along the software chain. Basically what we need to do is what Maurialia does (just copy the table), so we would have the same code in three cities. Ideas on how to refactor this things are welcomed.

Several test files should be updated. There is one failing test because `irene_bug_Kr_ACTIVE_7bar_RWF.h5` does not have the table. I'll try to regenerate that file later.

### CODE REVIEW

**Comment by jmbenlloch** [comment]
In the first commit a solution was implemented using two functions. The second commit does the same using a class to hide implementation details (user does not need to store mctrack table, row number, etc.). Test files are also updated. So basically this is done (only squash needed), tell me if you think anything should be changed.

**Comment by jmbenlloch** [comment]
Sorry, I thought I had already updated Diomira and Irene tests to check MCTrack table is written, but it seems I forgot. I will update this PR with them.

**Review by jjgomezcadenas — COMMENTED** [review]
The code contains at least a lie! :)!

**Review by jjgomezcadenas — COMMENTED** [review]
The doc of MCTrackWriter declares that this writer writes PMAPS... Which is good to get the enemy confused, but should probably be corrected.

**Comment by jmbenlloch** [comment]
Ok, that typo has been fixed.

I have also changed the test in diomira, before it was written in the same way as in Irene, but it didn't work. See for instance https://travis-ci.org/jmbenlloch/IC-1/jobs/209806549

This works in Irene but not in Diomira for reasons unkown to me:
```
mctracks_in  = h5in .root.MC.MCTracks[0]
mctracks_out = h5out.root.MC.MCTracks[0]
np.testing.assert_array_equal(mctracks_in, mctracks_out)
```

I have changed it in Diomira to this:
```
mctracks_in  = h5in .root.MC.MCTracks[0]
mctracks_out = h5out.root.MC.MCTracks[0]
for e in zip(mctracks_in, mctracks_out):
    np.testing.assert_array_equal(e[0],e[1])
```

Now it is supposed to be working.

**Comment by jjgomezcadenas** [comment]
A few suggestions: In Diomira:

```
 if not self.sipm_noise_cut:
            raise IOError('must set sipm_noise_cut before running')
```

I suggest adding an IC exception, "ParameterNotSet"

**Comment by jjgomezcadenas** [comment]
Concerning your test: have you tried assert_allclose? that should do the trick in both

**Review by jjgomezcadenas — COMMENTED** [review]
I don't see anything obviously wrong in the code, or the tests. The writer provides the functionality that we need to copy MCTracks downstream. 

From my side, OK, but I am letting @jacg decide if we approve or he wants to take a look first.

**Comment by jmbenlloch** [comment]
I have added the suggested exception in Diomira.

Regarding the test `assert_allclose` doesn't work. I think that function is used with float arrays, what we have here is this:

```
a = array((0, 0, b'e-', 11, [  3.06151588e-14,   0.00000000e+00,   2.51000004e+01], [ -0.19431403,  -0.09717072,  25.11500..., ('nof_hits', '<i4'), ('hit_indx', '<i4'), ('hit_position', '<f4', (3,)), ('hit_time', '<f4'), ('hit_energy', '<f4')])
b = array((0, 0, b'e-', 11, [  3.06151588e-14,   0.00000000e+00,   2.51000004e+01], [ -0.19431403,  -0.09717072,  25.11500..., ('nof_hits', '<i2'), ('hit_indx', '<i2'), ('hit_position', '<f4', (3,)), ('hit_time', '<f4'), ('hit_energy', '<f4')])
```

`assert_allclose` gives this error  `TypeError: invalid type promotion`.

I think the solution currently implemented in the test is working. If there are no more problems I will squash all commits so this is ready for approval.

**Comment by jacg** [comment]
There are conflicts after inclusion of #168. I tried to resolve them, but some bits aren't obvious to me. I'm sure @jmbenlloch can resolve them far more quickly and reliably.

Then please squash.

**Comment by jmbenlloch** [comment]
I have done the rebase and solved the conflicts. Also all commits are squashed now.

**Review by jacg — APPROVED** [review]

**Comment by jacg** [comment]
Travis is not running. I have run the tests on all our Python versions on Linux locally. They pass. So I'm going ahead and merging.

**Pull request merged**
