### PR TITLE
Sphinx documentation for core

### PR DESCRIPTION
**Pull request by jacg**
Another extract from #110.

Before accepting we need:

- [ ] review by @jacg

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
I don’t understand this… can I take this pull request or you need to review it (but you just submitted it)

**Comment by jacg** [comment]
As far as Github is concerned, *I* submitted it, but it's *your* code: it's the first commit of #110 (which has nothing to do with the real purpose of #110, which is why it needed to be removed from there).

So, even though I formally submitted this, the only person who has looked at this code so far is *you*. If you review and accept it, then that would simply avoid review.

**Review by jjgomezcadenas — DISMISSED** [review]

**Comment by jjgomezcadenas** [comment]
Ooppsss! Sorry!!! I understood it backwards and just reviewed it as positive… but I have not accepted yet, so you can always review it and accept it when you want.

**Comment by jacg** [comment]
Building the docs, gives the warning

`checking consistency... /home/jacek/src/IC/doc/core_doc.rst:: WARNING: document isn't included in any toctree`

Once that problem is solved, we get the warning

`/home/jacek/src/IC/doc/index.rst:11: WARNING: toctree contains reference to document 'core_doc' that doesn't have a title: no link will be generated`

Once *that* problem is solved, the docs build and the page is included, but it's extremely ugly. Part of the appeal of Sphinx is that it makes visually attractive documents, and this page is quite the opposite.

There is a random mix of `--`, `---` and `:`, which seem to be used interchangeably as (failed) attmepts to make something like a definition list.

I encourage @jjgomezcadenas to fix these problems, as an exercise in getting familiar with the basics of Sphinx and rst.

I will split this PR into two: the code changes will be extracted and accepted; `core_doc.rst` needs work.

**Comment by jacg** [comment]
As promised, this PR now contains `core_doc.rst` only. The code changes which originally were part of this PR have now been merged into master. @jjgomezcadenas, please clean it up at your leisure.

**Comment by jjgomezcadenas** [comment]
Nope, docs is the business of @jmbenlloch, my platter is really full…

**Comment by jjgomezcadenas** [comment]
@jmbenlloch please review this PR when you have the chance

**Comment by jmbenlloch** [comment]
I have corrected @jjgomezcadenas rst file. If there isn't anything wrong I think we can squash the two commits and approve this PR.

**Review by jmbenlloch — APPROVED** [review]

**Pull request merged**
