### PR TITLE
Ignore inline comments in config files

### PR DESCRIPTION
**Pull request by gonzaponte**
Example:
S1_LMIN 0 # This comment will be ignored

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
Very useful! Can you add a test, please?

**Comment by jacg** [comment]
Very quickly: I would recommend an approach based on `line.split('#',1)[0]`.

**Comment by gonzaponte** [comment]
I have implemented @jacg suggestion and use some inline comment in the config file used for testing.

**Comment by jjgomezcadenas** [comment]
Please squash and we can approve this PR

**Comment by gonzaponte** [comment]
Done

**Review by jmbenlloch — APPROVED** [review]
Again, tests are passing, but in travis there is an error with the installation of pytest-xdist 1.15.0 (issue #205). We can approve this.

**Pull request merged**
