### PR TITLE
Fix skipped test

### LINKED ISSUE #560: Review skipped tests
In order to speed the process of refactoring liquid cities, we have skipped a number of troublesome tests. Many of them are histograms, which need to go to a different place (separate issue) but all the rest need to be reviewed. I propose that this is done by @bpalmeiro, and @carmenromo (with the guidance of @gonzaponte). "Review" here means identifying the author of the skipped test and ask him or her to fix it, then keep log of the tests that are being fixed. Please proceed without delay, this is an important issue that should not be left hanging.

### PR DESCRIPTION
**Pull request by bpalmeiro**
In order to speed the process of refactoring liquid cities, we have skipped a number of troublesome tests. @carmenromo and I will ask the authors of these tests for the proper changes.

This PR closes #560

### CODE REVIEW

**Comment by carmenromo** [comment]
There are some liquid_cities written that have some skipped tests: `diomira`, `dorothea`, `irene`, and `penthesilea`. @jacg and @gonzaponte could you please review them?

**Comment by gonzaponte** [comment]
> There are some liquid_cities written that have some skipped tests: `diomira`, `dorothea`, `irene`, and `penthesilea`. @jacg and @gonzaponte could you please review them?

The following tests are skipped because they are related to deprecated features (or similar) and will be removed wither in this PR or in another:
- `test_diomira_fee_table`
- `test_event_number_from_input_file_name`
- `test_dorothea_issue_347`
- `test_dorothea_event_not_found`
- `test_irene_electrons_40keV_pmt_active_is_correctly_set`
- `test_irene_split_trigger`
- `test_penthesilea_event_not_found` (related to #564)

I will review the remaining:
- `test_diomira_trigger_on_masked_pmt_raises_ValueError`
- `test_irene_empty_pmap_output`

and ensure they are skipped for a good reason.

**Comment by bpalmeiro** [comment]
test_get_chi2_and_pvalue_gauss_errors was skipped but I ran it several times with --hypothesis-profile=hard and max_examples up to 1e4 and no failure was found, Travis didn't complain also. @jacg, was there any special reason I am not getting for skipping this test or is it fine to restore it?

**Comment by jacg** [comment]
You were lucky (or unlucky). This test fails every now and then ... usually on a Travis build at the most inconvenient time. The test is statistical in nature and therefore has a nonzero probability of spurious failure. This is a huge PITA. It cannot continue like this.

**Comment by bpalmeiro** [comment]
Okay. My guess would be mark it as flaky, allowing it fails one out of four. Would it work for this?

**Comment by jjgomezcadenas** [comment]
@bpalmeiro, @carmenromo, please report on the status of this. If done, please rebase.

**Comment by mmkekic** [comment]
What is the status of the skipped test? @gonzaponte ? I'd suggest we mark this particular test as flaky, as was done with the others statistical tests, as @bpalmeiro  proposed

**Comment by gonzaponte** [comment]
Ok

**Comment by gonzaponte** [comment]
`test_diomira_trigger_on_masked_pmt_raises_ValueError` and  `test_irene_empty_pmap_output` are done

**Review by carmenromo — APPROVED** [review]

**Comment by carmenromo** [comment]
This PR cleans test code left after the transition to liquid cities. It has been reviewed with peras, so approved!

**Pull request merged**
