### PR TITLE
Upload database

### PR DESCRIPTION
**Pull request by carmenromo**
In this PR database is uploaded with new gains for SiPMs based on the calibrations from run 6358.

### CODE REVIEW

**Comment by carmenromo** [comment]
sipmrundifferenceplots

Here is the difference of the most important parameters with previous runs.

**Comment by gonzaponte** [comment]
Two minor comments:
- I think it would be helpful to produce the plots with the same binning for both distributions
- Shouldn't the range of the mu distribution difference display also negative values?

**Comment by jmbenlloch** [comment]
There were two failing tests checking the exact result produced by diomira and irene. Those results are dependant on the DB used. The run number was one to high (10000), meaning "the lastest one", but the meaning of that varies along time. I have fixed those run numbers to a particular value that gives the same calibration that was obtained at the time that those tests were created. Every new calibration will give slightly different results, so we have to be careful with this.

With my last commit all test should be passing. If that is the case, everything is ok from my side. @carmenromo you may want to address @gonzaponte 's comments, when everything is clear we can approve.

**Comment by gonzaponte** [comment]
Good catch!

**Comment by carmenromo** [comment]
sipmrundifferenceplots

The binning is fixed here

**Comment by carmenromo** [comment]
> Shouldn't the range of the mu distribution difference display also negative values?

@andLaing do you know how can this be?

**Comment by andLaing** [comment]
How do you make the histogram? Do you set bins or just use pyplot.hist?

If the second, it's just that in this case the one with more light is 'a' in 'a-b', if not, we could be chopping values.

In any case that plot is the least interesting since it's run dependent. It's useful to check that the run conditions are the same for two runs with the same LED settings but the gain and 1pe sigma are the parameters that we're uploading and the chi^2 checks that we're getting reasonable fits

**Comment by carmenromo** [comment]
pmtrundifferenceplots

PMT plot comparison

**Comment by carmenromo** [comment]
@jmbenlloch now you can approve, tests are fixed with #577

**Review by jmbenlloch — APPROVED** [review]
This PR includes the latest calibration for both SiPMs and PMTs and the issues with some tests has already been solved in another PR, therefore I approve.

**Pull request merged**
