### PR TITLE
Safety check for liquid cities' sources

### PR DESCRIPTION
**Pull request by gonzaponte**
Introduce a safety check to the liquid cities sources to ensure all the accessible and relevant fields in the input file have the same length. This way we minimize the possibility of a mismatch among the data pushed through the pipes.

### CODE REVIEW

**Comment by gonzaponte** [comment]
Do you have the time to take a look to this, @jacg?

**Comment by jacg** [comment]
> Do you have the time to take a look to this, @jacg?

I'm afraid not. This would require me to string together more than 30s of careful, uniterrupted thought. Unfortunately I won't have that available to dedicate to IC for weeks to come.

**Comment by jjgomezcadenas** [comment]
@gonzaponte this is a difficult one. Shall we work con peras to review it?

**Comment by gonzaponte** [comment]
How & when? I’ll be on shift next week.

**Comment by jjgomezcadenas** [comment]
OK, we can skype next week at a convenient time.

**Comment by gonzaponte** [comment]
Ok, I'll be in touch and try to set a time depending on the work we have there.

**Review by jjgomezcadenas — APPROVED** [review]
Reviewed with peras, very good stuff, trademark of the house. Good job.

**Pull request merged**
