### PR TITLE
reintroduced sensor info in calibration output

### PR DESCRIPTION
**Pull request by andLaing**
sensor information copied from raw waveform
files to output for:

berenice (sipm pdfs)
phyllis  (pmt pe_to_adc)
trude    (sipm pe_to_adc)

### CODE REVIEW

**Comment by andLaing** [comment]
Neus needs this for start-up tests on demo++ so if a quick turn around is possible it'd be preferred

**Comment by andLaing** [comment]
Neus needs this asap for demo, @jmbenlloch , @gonzaponte , @jjgomezcadenas , por favor!!

**Review by gonzaponte — APPROVED** [review]
Looks good.

Seems weird that `cf.copy_sensor_table` takes a *filename* and a *file*, but otherwise is ok.

**Comment by jacg** [comment]
> Neus needs this asap 

If she needs it to produce some results, then she can do that witout it being approved and merged, simply by checking out this branch.

**Comment by gonzaponte** [comment]
Please, add a test to each city to ensure the table is written (can be done in some other PR if you are in a hurry)

**Comment by andLaing** [comment]
> > Neus needs this asap
> 
> If she needs it to produce some results, then she can do that witout it being approved and merged, simply by checking out this branch.

It's for the demo frontend installation, I'm not sure they want to be making multiple branches there but in the short term maybe they can just do that

**Comment by andLaing** [comment]
> Looks good.
> 
> Seems weird that `cf.copy_sensor_table` takes a _filename_ and a _file_, but otherwise is ok.

I think this was due to some requirement/bothersome structure in the old 'solid' cities. I just reinstated the use of the function in these cities since it was something that was relatively urgent. I'll look to see if it can be improved when I add the tests.

**Pull request merged**
