### PR TITLE
Blob class fix

### PR DESCRIPTION
**Pull request by paolafer**
In this PR I fix a couple of bugs in the `Blob` class definition, which had escaped previous reviews because there was no test for this class. Therefore, I've also added a test for the `make_tracks`function, which is the only function that uses the `Blob` class, and which was lacking its own test.

### CODE REVIEW

**Comment by paolafer** [comment]
For some reason, a commit that has nothing to do with this PR (444b942) has sneaked in.
Could some expert have a look at it and possibly remove it? Thanks!

**Comment by jmbenlloch** [comment]
> For some reason, a commit that has nothing to do with this PR (444b942) has sneaked in.
Could some expert have a look at it and possibly remove it? Thanks!

Done! You could do an interactive rebase, reorder the commits leaving 444b942 as the last one, and the reset your branch to the previous one. Since there are no conflicts you can do that reordering without any problem.

**Comment by paolafer** [comment]
I think I managed to remove the wrong commit, but maybe @jmbenlloch was faster than me :-). I'm not sure what has happened now :-).

**Review by jjgomezcadenas — APPROVED** [review]
Good catch again, and a book example of the need of tests for functions.

**Comment by jjgomezcadenas** [comment]
@paolafer please rebase then @bpalmeiro or @carmenromo pleaase merge

**Pull request merged**
