### PR TITLE
Adds functions for Paolina algorithm and tests

### PR DESCRIPTION
**Pull request by jerenner**
This requires the additional package networkx (available in Conda)

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
@jerenner tests are failing... do you know why?

**Comment by jmbenlloch** [comment]
I have added the package networkx to the package list that we install in our environment, but that is not why tests are failing. The error is:

```
ImportError while importing test module '/home/jmbenlloch/next/IC-1/invisible_cities/reco/paolina_functions_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
invisible_cities/reco/paolina_functions_test.py:3: in <module>
    from   invisible_cities.reco.dst_io import Hit, HitCollection
E   ImportError: cannot import name 'Hit'
```

Hit and HitCollection are not defined in `invisible_cities.reco.dst_io` (nor anywhere else), maybe @jerenner forgot to add that changes in the commit?

**Review by jjgomezcadenas — DISMISSED** [review]
needed for Josh's version of PAOLINA

**Comment by jjgomezcadenas** [comment]
@jmbenlloch I have approved the addition of networkx library, but tests fail...

**Comment by jmbenlloch** [comment]
Adding networkx package is part of the same PR as Paolina. Tests keep falling because Hit and HitCollection are not defined, @jerenner needs to make a commit including those changes in dst_reco.

**Comment by jjgomezcadenas** [comment]
Sorry, I didn't realise that this is the same PR than Josh's Paolina. We then need to add HitCollection, etc to the PR. Please @jerenner, talk to @gonzaponte to do it properly!

**Comment by jerenner** [comment]
I've modified dst_io to match that of the Penthesilea branch.  @gonzaponte please let me know if this was not the correct thing to do.  Now it looks like the tests are failing because networkx is not present.

**Comment by jmbenlloch** [comment]
@jerenner, the commit I made was removed when you uploaded your merge. I have changed that to a rebase and reapplied my commit including networkx. The test now pass.

**Comment by jerenner** [comment]
@jmbenlloch, thanks.  Sorry I didn't realize I had removed your commit.

**Review by jjgomezcadenas — APPROVED** [review]
This is a major piece of work that implementes de "Paolina" (actually Breadth First Search) algorithm, using the networkx graph library. 

The text corresponds to a brave attempt, by @jerenner   to implement both the code and the tests of the Paolina algorithm. While conceptually correct (we haven't identified bugs and the tests run correctly), there is a new implementation by @jacg, which displays higher level and more in-depth testing. We will take @jacg implementation but this review raises @jerenner level of Karma by 10 points. 

We formally APPROVE this PR, although it will not be actually part of the main repository line (it will go to a line called ARCHIVE which is intended to keep track of interesting development).

**Pull request merged**
