### PR TITLE
Update DB to use the same tables used in ART software.

### PR DESCRIPTION
**Pull request by jmbenlloch**
So far we have been using different databases in NEXT software. This PR changes our code to use the tables structure used in ART, so in the future we don't have two keep updating two databases whenever there is a new calibration, etc.

### CODE REVIEW

**Review by jjgomezcadenas — COMMENTED** [review]
This is a much needed technical upgrade. I see that no new tests are added. Are u satisfied with the level of testing here?

**Comment by jacg** [comment]
Unless you have some very specific questions for me, I will ignore this PR. I am too unfamiliar with this part of IC, and I have too much on my plate before I disappear for two weeks at the end of this one.

**Comment by jmbenlloch** [comment]
@jacg no problem.

@jjgomezcadenas you are right. I have modified existing tests to check not only the number of sensors but also the properties appearing in the pandas dataframe.

**Review by jjgomezcadenas — APPROVED** [review]
OK, we go ahead with this.

**Comment by jmbenlloch** [comment]
I forgot to remark one important thing. Everybody has to download again the database. So please execute: `source manage.sh download_test_db` after fetching nextic/master.

**Pull request merged**
