### PR TITLE
Fix missing `gain_mau` option in pmtgain

### PR DESCRIPTION
**Pull request by andLaing**
Re-added function for the second option which
had been removed accidentally in previous
PR review.

### CODE REVIEW

**Comment by andLaing** [comment]
The fail is related to another PR according to @paolafer so I'll rebase once it's approved.

**Comment by jjgomezcadenas** [comment]
I don't understand how another PR is making yours fail... @paolafer can you explain?

**Comment by andLaing** [comment]
The other PR seeks to sort the error.

**Comment by paolafer** [comment]
The PR Andrew is talking about is #457.

**Comment by gonzaponte** [comment]
#457 has been merged. Please rebase.

**Comment by andLaing** [comment]
another odd error, unrelated to the changes in the PR that doesn't fail in local... thoughts, @gonzaponte ?

**Comment by gonzaponte** [comment]
I've launched a rebuild. These failures are annoying me, but since they have nothing to do with the PR, I will "ignore" them for the moment.

**Comment by gonzaponte** [comment]
Can you please add a test that at least uses that option in the processing?

**Review by gonzaponte — APPROVED** [review]
Perfect. Fixes functionality + extends test suite to avoid this kind of mistakes in the future.

**Comment by gonzaponte** [comment]
Somehow Travis has disappeared from this PR

**Comment by andLaing** [comment]
I think you approved before I did the rebase ,could it be because of that?

**Comment by gonzaponte** [comment]
I did, but I think that doesn't change the fact that any push to the source branch triggers a Travis build.

**Comment by gonzaponte** [comment]
It passed before so it can be merged anyway, but it is weird...

**Comment by paolafer** [comment]
@andLaing managed to beat Travis! Yeah!

**Pull request merged**
