### PR TITLE
Add MC Timestamp Generator

### LINKED ISSUE #752: Generating MC timestamps
In the past we've tended to set the timestamp required information in the Run tables to zero for all events in MC runs. This is not ideal if we want to be able to study tagging of muons or other time related vetos in the future.

We should probably generate time stamps based on some user configured trigger rate to allow for more data-like vetoing in these cases. This should be simple enough to implement and, as long as the user doesn't try for a rate >~1 kHz leaves ample space for any long duration events that could be split into multiple triggers.

Also could be a nice easy first PR for someone.

### PR DESCRIPTION
**Pull request by MCruces-fz**
With the intention of adding a function that generates timestamps, this push is presented with the following changes:

  - Updated `sensor_utils.py` with the `create_timestamp` function.
  - Added `test_create_timestamp_greater_with_greater_arguments` to `sensor_utils_test.py` with the intention of testing whether with larger parameters said timestamp is greater.
  - Updated `buffy.conf`, `buffy.py` and `components.py` to implement the function `create_timestamp`.

Fixes #752

### CODE REVIEW

**Comment by jacg** [comment]
Hi,

Thanks for the PR.

There are a few things you seem to be doing, in terms of usage of Git, which go against the practices we have adopted in IC:

1. We always develop features on named feature branches, rather than `master`.

2. We never merge `master` into the branches on which we develop (so that last commit will have to go).

Do you have someone you can talk to locally about our development practices?

**Comment by MCruces-fz** [comment]
Hi,

I'm sorry, I will try to change these errors:
1. I have developed these changes in my add_timestamp branch, but then I merged it with master, so I can make the pull request from that branch.
2. I haven't merge master to add_timestamp branch, so I think this second error will be arranged.

I can talk to @mmkekic and ask her about good development practices. Thank you.

**Comment by jacg** [comment]
Don't close this PR or open a new one just yet ...

**Comment by jacg** [comment]
... OK, go ahead, close this PR, open a new one from your `add_timestamp` branch. If you can rebase `add_timestamp` on `upstream/master` (after fetching the latest) before opening the new PR, that would be great. If not, it's not a tragedy, but we rebase onto `upstream/master` before merging, so you might as well get used to the process, as it's something you will want to do in any long-lived development branches that you have.

**Comment by MCruces-fz** [comment]
OK thanks for the help. I hope I am able to do all of that right. Cheers!

**Pull request closed without merging**
